### PR TITLE
Fix inconsistent connections when using Timeout under MRI 2.1+.

### PR DESCRIPTION
**Pull request by djanowski**
This should address #501.

I like this solution because the performance and complexity penalty of keeping counters is limited to the pure Ruby driver. Edit: From the comments below, I'll test what happens with Hiredis (I thought it wasn't an issue).

The 'test cases' were [this](https://gist.github.com/tarcieri/303c5dcf803b0e5d021d) and [this](https://gist.github.com/stevehodgkiss/10204388). I'll try to make those proper tests cases in our code base.

### CODE REVIEW

**Comment by tamird** [comment]
can you add some test cases to demonstrate that this is correct?

**Comment by tamird** [comment]
i believe in our experience hiredis was also vulnerable to this issue -- is that meant to be addressed here?

**Comment by mperham** [comment]
Can't any driver become corrupt or does hiredis already perform similar checks?

**Comment by djanowski** [comment]
@tamird Just updated the PR description with links to the 'test cases' that I used (originally posted on #501). I'll try to make them proper tests in our code base.

Also, I thought from @tarcieri's comment that Hiredis wasn't an issue, but I'll look into it (in fact my first take at this fixed all drivers, but I took another approach in order to make just the Ruby driver pay the penalty).

**Comment by djanowski** [comment]
@mperham ^^^

**Comment by tarcieri** [comment]
@djanowski it's a problem if you use Timeout with hiredis. I was saying that hiredis implements its own timeouts using asynchronous I/O and those are fine.

**Comment by djanowski** [comment]
@tarcieri Yes I understood that afterwards. Since it provides native timeouts, there's usually no need to use external `Timeout.timeout` calls.

OK, I'll go ahead and fix hiredis too. May still have my original implementation in a stash.

**Comment by djanowski** [comment]
@igrigorik If you think the Synchrony driver is affected by this, please chime in.

**Comment by yaauie** [comment]
I think this approach makes a lot of sense, and that the additional overhead is both small & justified. :+1:

**Comment by fw42** [comment]
Thanks a lot for this fix, we ran into the same issue under high load.

**Comment by fw42** [comment]
Any idea when there will be a Rubygems release available that includes this change?

**Comment by badboy** [comment]
As soon as @djanowski pushes it ;)

**Comment by djanowski** [comment]
Will look into this in the next 24 hours

**Pull request merged**
