### PR TITLE
Avoid Fixnum deprecation warning on Ruby trunk

### PR DESCRIPTION
**Pull request by utilum**

### CODE REVIEW

**Comment by irobayna** [comment]
Any chance we can merge this item?

**Comment by badboy** [comment]
Let me grab 2.4-rc1 and see for myself. Otherwise I don't see why not.

**Comment by badboy** [comment]
Thanks @utilum for the patch, thanks @irobayna for the reminder.

**Comment by matthewrudy** [comment]
Any chance of getting a release of this?
Would be great to have ruby 2.4.0 running without any deprecations

**Comment by badboy** [comment]
Hm, we should probably get [4.0](https://github.com/redis/redis-rb/pull/653) out of the door.

**Comment by manuelmeurer** [comment]
Would love to see v3.3.3 with this change released! 😄

**Comment by vincentwoo** [comment]
Just to echo the sentiments here in case this got forgotten in the holiday shuffle, I think a tiny patch release just so we can silence the deprecation warnings would be great!

**Comment by georgemillo** [comment]
Just so everyone knows, it looks like 3.3.3 contains the above commit. It's not reflected in the  changelog for 3.3.3, but I just submitted a PR to add it ;)

**Comment by matthewrudy** [comment]
@georgemillo yep
I switched to 3.3.3 a while ago,
works for me!

**Pull request merged**
