### PR TITLE
Custom reconnect_attempts to Fixnum

### PR DESCRIPTION
**Pull request by otoyo**
string won't be expected at https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L371.

### CODE REVIEW

**Comment by HirokiToyokawa** [comment]
retest this please

**Comment by otoyo** [comment]
@badboy Would you be able to review this, please?

**Comment by badboy** [comment]
Remind me in about 7 weeks again. 🌴 🌞

**Comment by otoyo** [comment]
OK. Have a nice vacation. 🏝

**Comment by otoyo** [comment]
@badboy 7 weeks passed 🌞

**Comment by badboy** [comment]
@otoyo Thanks for the reminder! It's weekend, so I'm pushing this on my list for next week!

**Comment by otoyo** [comment]
oh.. 😇

**Comment by badboy** [comment]
Test failures are unrelated. Hmpf.

**Comment by badboy** [comment]
I'm gonna take care of this later.

**Pull request merged**
