### PR TITLE
Write nonblock

### PR DESCRIPTION
**Pull request by badboy**
This should fix the latest leaks due to the way the timeout module spawns threads.

I used the following test to verify, but I'm not 100% sure it is reliable.
I'm still sure the code is actually correct ([tcp-timeout](https://github.com/lann/tcp-timeout-ruby) uses it as well). It's definitely better than using Timeout.

```ruby
driver(:ruby) do
  def test_write_timeout
    server = TCPServer.new("127.0.0.1", 0)
    port   = server.addr[1]

    # Hacky, but we need the buffer size
    val = TCPSocket.new("127.0.0.1", port).getsockopt(Socket::SOL_SOCKET, Socket::SO_SNDBUF).unpack("i")[0]

    assert_raise(Redis::TimeoutError) do
      Timeout.timeout(1) do
        redis = Redis.new(:port => port, :timeout => 5, :write_timeout => 0.1)
        redis.set("foo", "1" * val*2)
      end
    end
  end
end
```

### CODE REVIEW

**Comment by badboy** [comment]
I added the test code, so it at least runs on Travis once. I can still take it out before merging if it is too unrealiable.

**Comment by djanowski** [comment]
Great! I'll try to review tomorrow, along with checking of benchmarks.

**Comment by badboy** [comment]
Test failures due to problems in Ruby 1.8.7 and flaky tests in jruby (plus JRuby in 1.8 mode).
I'm in favor of dropping 1.8 support immediately, though I understand that we might want to still make the next patch release work on 1.8.7 (that's why I added a monkey-patch to have a somewhat similar `byteslice` in Ruby <1.9

**Comment by badboy** [comment]
Can we pull this in?

**Comment by badboy** [comment]
This change seems to not work on jruby (using the above test). Everything else is green though.
I'm disabling the test for now.

Old results: https://travis-ci.org/redis/redis-rb/builds/143895633

**Comment by badboy** [comment]
cc @djanowski

**Pull request merged**
