### PR TITLE
Fix testing of redis branches

### PR DESCRIPTION
**Pull request by byroot**
While trying to figure out further optimizations, I noticed that jobs with `REDIS_BRANCH=3.0` were actually building `unstable`.

I though I broke it in #757, but actually looking at older builds the issue was already here, e.g.: https://travis-ci.org/redis/redis-rb/jobs/280892409

```bash
export REDIS_BRANCH=3.0
#....
wget https://github.com/antirez/redis/archive/unstable.tar.gz -O tmp/redis-unstable.tar.gz
```

Again my makefile foo isn't great, but this change seem to work.

### CODE REVIEW

**Comment by byroot** [comment]
Hum. It seems like there is 12 broken tests with `REDIS_BRANCH=3.0`, I'll see if I can fix them.

**Comment by byroot** [comment]
I marked the tests as skipped for Redis < 3.2.0.

**Comment by rafaelfranca** [comment]
Oh. Looks like unsable is now failing.

**Comment by ajlai** [comment]
Perhaps we should avoid building the unstable branch or move it to allowed failures?
It looks like unstable failing is also happening in redisci: http://ci.redis.io/run_66863.html

**Pull request merged**
