### PR TITLE
Distributed sscan and sscan_each

### PR DESCRIPTION
**Pull request by jhollinger**
Adds `sscan` and `sscan_each` to `Redis::Distributed`. Just simple proxy methods.

### CODE REVIEW

**Comment by badboy** [comment]
Could you add tests?

**Comment by jhollinger** [comment]
Tests added

**Comment by jhollinger** [comment]
Bump any news on this?

**Comment by jhollinger** [comment]
Since it's been 2 years I've rebased against master and pushed up again. Tests are still passing. Rather, test output is unchanged from master (1 failure `test/internals_test.rb:343:in 'test_connecting_to_unix_domain_socket'`), but that's unrelated to my changes. Anything else I can do to get this merged? Would really love to get off of our fork.

**Comment by badboy** [comment]
The future of `Redis::Distributed` is currently unclear. We might deprecate it. Thus at the moment we are not gonna merge additional features for it.

**Comment by jhollinger** [comment]
Is that perhaps in favor of Redis Cluster support?

**Comment by djanowski** [comment]
In the end we'll continue to support Redis::Distributed for a while.

This will be out in the form of ~4.0.1.

Thank you very much.

**Pull request merged**
