### PR TITLE
Reduce `Proc` object allocations.

### PR DESCRIPTION
**Pull request by marshall-lee**
It's also  a kind of refactoring: it removes private methods that actually are not methods of `Redis` instance since they don't depend on its state.

### CODE REVIEW

**Comment by djanowski** [comment]
Been wanting to make this change for a long time. Will merge soon.

**Comment by marshall-lee** [comment]
Let's merge it!

**Comment by davydovanton** [comment]
:+1:

**Comment by marshall-lee** [comment]
@djanowski  Bump!

**Pull request merged**
