### PR TITLE
Add Redis 6.2 to the GitHub Actions test suite

### PR DESCRIPTION
**Pull request by rhymes**
Refers to https://github.com/redis/redis-rb/issues/978

### CODE REVIEW

**Comment by byroot** [comment]
Sorry but that's not the way to do it. Testing all redis versions against all ruby version creates a giant matric that takes agests to complete.

Just set Redis version to 6.2 in the original main matrix, and add 6.0 in other matrix.

**Comment by rhymes** [comment]
@byroot, will do! Thanks for the feedback!

**Comment by byroot** [comment]
Might want to rebase, I pushed a CI fix.

**Comment by rhymes** [comment]
@byroot sorry for taking so long to circle back on this. I fixed the errors :-)

**Pull request merged**
