### PR TITLE
Add geo commands

### PR DESCRIPTION
**Pull request by TheSmartnik**
I've added keyword arguments to `georadius` and `georadiusbymember` as discussed in  #711. Don't know whether to add `GEOADD`, `GEODIST`, `GEOHASH`, `GEOPOS`

### CODE REVIEW

**Comment by TheSmartnik** [comment]
@badboy Hi, not asking you to review code, just a quick tip. Should I add commands for `GEOADD`, `GEODIST`, `GEOHASH`, `GEOPOS` as well?

**Comment by badboy** [comment]
Please do so! I’d be happy to merge these, code looks easy enough for me to review ;)

**Comment by TheSmartnik** [comment]
@badboy thanks for reply! I've added the rest of geo commands. Would love to hear your feedback 😄

**Comment by badboy** [comment]
Looks good to me.

**Comment by TheSmartnik** [comment]
@badboy can you merge this, then?

**Comment by badboy** [comment]
Tests weren't finished before and now some are broken. I'll see that I spend some time later on fixing that (failures seem unrelated to your code, but due to our flaky test setup...)

**Comment by badboy** [comment]
I, uuuh, ... force-pushed the rebased PR to your branch. I hope I didn't overstep, sorry.
Tests are now running again and I can merge afterwards.

**Comment by badboy** [comment]
I'm gonna debug the remaining test failures next week. They are unrelated to this change.

**Comment by TheSmartnik** [comment]
Thanks! 👍

**Pull request merged**
