### PR TITLE
Add spop count support

### PR DESCRIPTION
**Pull request by ceritium**
Copied from https://github.com/redis/redis-rb/pull/621 but passing tests.

All merits to @arashbm

### CODE REVIEW

**Comment by mrinterweb** [comment]
SPOP optional count argument is available in Redis 3.2. This commit looks good to me.

**Comment by pedrocunha** [comment]
It would be great to have this on master. Thank you

**Comment by theorygeek** [comment]
@badboy Any timeline on getting this merged?

**Comment by badboy** [comment]
Merging now, not sure when we cut a release

**Pull request merged**
