### PR TITLE
Sentinel tests + Hiredis fix

### PR DESCRIPTION
**Pull request by djanowski**
Adds some tests to cover sentinel support.

### CODE REVIEW

**Comment by djanowski** [comment]
@badboy I cherry-picked badboy/redis-rb@fa1abe727712f2efcbebd38f56bd28233f2b6088 to make this PR pass. Anything else we need to cover?

**Comment by djanowski** [comment]
@badboy Sorry, I hadn't seen the other commits on the other branch. Kind of reimplemented the fix for UDS. But I saw you restored the short timeout. This was @antirez original implementation, but I'm not sure if we should just honor whatever timeout is given in options. Any ideas?

**Comment by djanowski** [comment]
@sixfeeover 2c07679b54e8583d2382b2acc6485179fae2b888 shows that sentinel support works with authentication. Am I missing something?

**Comment by badboy** [comment]
With all this mock code we don't actually test the same thing Redis does.

```
[2] pry(main)> sentinels = [{:host => "127.0.0.1", :port => 26381}]
=> [{:host=>"127.0.0.1", :port=>26381}]
[3] pry(main)> redis = Redis.new(:host => "master1", :password => "foo", :sentinels => sentinels, :role => :master)
=> #<Redis client v3.2.0 for redis://master1:6379/0>
[4] pry(main)> redis.ping
Redis::CommandError: ERR unknown command 'auth'
from /home/badboy/code/redis-rb/lib/redis/client.rb:113:in `call'
[5] pry(main)> redis = Redis.new(:host => "master1", :sentinels => sentinels, :role => :master, :db => 1)
=> #<Redis client v3.2.0 for redis://master1:6379/1>
[6] pry(main)> redis.ping
Redis::CommandError: ERR unknown command 'select'
from /home/badboy/code/redis-rb/lib/redis/client.rb:113:in `call'
```

The problem is: we're still passing on all options, even to sentinel connects, which in turn goes through the whole code again, parsing options, applying auth and select.
What we need to do: strip all non-sentinel options before passing them on (db, password, not sure if more).
What we could also do: seperate connection options (host, port, path, connect_timeout, more?) from client options (the ones Sentinel does not need)

**Comment by badboy** [comment]
```diff
diff --git i/test/sentinel_test.rb w/test/sentinel_test.rb
index 94e4fd9..a1931b4 100644
--- i/test/sentinel_test.rb
+++ w/test/sentinel_test.rb
@@ -119,6 +119,10 @@ class SentinalTest < Test::Unit::TestCase
     }
 
     sentinel = {
+      :auth => lambda do |pass|
+        commands[:s1] << ["auth", pass]
+        "-ERR unknown command 'auth'"
+      end,
       :sentinel => lambda do |command, *args|
         commands[:s1] << [command, *args]
         ["127.0.0.1", "6382"]
@@ -138,7 +142,7 @@ class SentinalTest < Test::Unit::TestCase
 
     RedisMock.start(master, {}, 6382) do
       RedisMock.start(sentinel, {}, 26381) do
-        redis = Redis.new(:url => "redis://:foo@master1", :sentinels => sentinels, :role => :master)
+        redis = Redis.new(:host => "master1", :password => "foo", :sentinels => sentinels, :role => :master)
 
         assert redis.ping
       end
```

Also we should swap the arguments for `assert_equal`, makes for nicer failure messages:

```diff
diff --git i/test/sentinel_test.rb w/test/sentinel_test.rb
index 94e4fd9..ac60b83 100644
--- i/test/sentinel_test.rb
+++ w/test/sentinel_test.rb
@@ -144,8 +144,8 @@ class SentinalTest < Test::Unit::TestCase
       end
     end
 
-    assert_equal commands[:s1], [%w[get-master-addr-by-name master1]]
-    assert_equal commands[:m1], [%w[auth foo], %w[role]]
+    assert_equal [%w[get-master-addr-by-name master1]], commands[:s1]
+    assert_equal [%w[auth foo], %w[role]], commands[:m1]
   end
 
   def test_sentinel_role_mismatch
```

**Comment by djanowski** [comment]
Perfect, that's why I needed your input ;)

Looking into it.

**Comment by djanowski** [comment]
@badboy See added commits, thanks.

**Pull request merged**
