### PR TITLE
Accept sentinel options even with string keys

### PR DESCRIPTION
**Pull request by lucaong**
Before, the sentinel options were assumed to have symbol keys, so string keys
were ignored. This is surprising, as other Redis options can be indifferently
passed as symbols or strings. Now string keys are allowed too.

### CODE REVIEW

**Comment by yagilm** [comment]
+1

**Comment by lucaong** [comment]
Travis specs fail on Ruby `1.8.7` due to:

```
Gem::InstallError: rake requires Ruby version >= 1.9.3.
An error occurred while installing rake (11.1.1), and Bundler cannot continue.
Make sure that `gem install rake -v '11.1.1'` succeeds before bundling.
```

This is not related to the code changes though. Tests pass locally, but I would love to see the build pass on different Ruby versions on Travis. Could this be an issue with the version of `test_unit`?

**Comment by badboy** [comment]
More the fact that we don't restrict the rake version and therefore the latest one is pulled which is now incompatible with Ruby 1.8.7

We will pull the plug on 1.8.7 eventually.

**Comment by lucaong** [comment]
I see ;)

**Comment by lucaong** [comment]
It is possible to fix this by adding, in the gemspec, something like this:

```ruby
if RUBY_VERSION == "1.8.7"
  s.add_development_dependency "rake", "~> 10.0"
else
  s.add_development_dependency "rake"
end
```

That would make the build run. Should I do that as part of this PR, or separately, or skip it completely?

**Comment by badboy** [comment]
I don't like the conditional there. We don't depend on any newer features, so we can stick with 10.0 for all Ruby versions for now (this is only a development dependency and should not cause trouble to other gems)

**Comment by lucaong** [comment]
OK, tests are passing now. I also had to make sure a recent version of bundler is used for CI, to fix failures on jRuby head. And close/reopen PR to force Travis to rebuild.

**Comment by keeganlow** [comment]
just helped someone who got burned by this issue - seems like the concerns about rake version mentioned above should be addressed now, since https://github.com/redis/redis-rb/pull/601 is now in master.

Would this PR be ready to merge if we remove the parts that deal with the rake version? Happy to submit a modified PR myself if that helps.

**Comment by alexpapworth** [comment]
Any chance we can get this PR finished off and approved?

**Comment by lucaong** [comment]
As far as I know, this is finished (tests were passing), although I sent it 4 years ago so things might have changed?

**Comment by lucaong** [comment]
I took care of rebasing on the current master and fixing the conflicts, as a few things changed since this PR was open.

**Comment by alexpapworth** [comment]
Awesome! Can we get a member of the Redis team to review?

cc: @byroot

**Pull request merged**
