### PR TITLE
Ensure connections are closed when client is GC'd

### PR DESCRIPTION
**Pull request by badboy**
DO NOT MERGE!

See https://github.com/redis/redis-rb/issues/524

### CODE REVIEW

**Comment by badboy** [comment]
This _does_ close the connections, but it seems we're leaking internal objects somehow, otherwise the tcp connection would be closed on GC anyway. Investigating further.

**Comment by kaspergrubbe** [comment]
@badboy Did your investigations yield anything?

**Comment by badboy** [comment]
I don't think so. That was 4 years ago. I don't maintain this project anymore.

**Pull request closed without merging**
